### ISSUE TITLE
Developer Programme Agreement - Internal server error

### ISSUE THREAD

**Issue by bunniseng** [canonical/snapcraft.io#4572]
### Expected behaviour

When accepting the developer programme agreement and clicking continue, I am taken to the snapcraft portal.

### Steps to reproduce the problem

Create a new account
Verify email
Attempt to accept the developer programme agreement

### Specs

- _URL: https://snapcraft.io/account/agreement
- _Operating system: OSX 14.2.1
- _Browser: Firefox

**Comment by bunniseng** [comment]
@shivjoshi1996 Would you be able to look at this issue ? at the moment no new users are able to sign up due to the developer agreement workflow bug.

**Comment by chillkang** [comment]
@bunniseng I'll take a look into this!

**Comment by chillkang** [comment]
@bunniseng Could you let me know what you mean by the snapcraft portal?

**Comment by pidpawel** [comment]
snapcraft.io. Happens on a new account, trying to log-in, after email confirmation. URL of the error is: https://snapcraft.io/account/agreement

**Comment by steverydz** [comment]
@pidpawel I was able to reproduce this, but after logging out and then back in it worked. Can you verify if this works for you?

**Comment by pidpawel** [comment]
Actually I seem to have managed to use a different workaround - I've used a https://dashboard.snapcraft.io/ directly (which, I as far as I remember, asked for a different document, accepted it, created a snap, uploaded it aaand… now I don't have an agreement form on https://snapcraft.io
I can, however, manually go to https://snapcraft.io/account/agreement, sign it and… then be successfully redirected to user/main page. (And I can now go through this workflow multiple times.)

**Comment by steverydz** [comment]
@pidpawel This is fixed now. It was a case of the user not being authenticated when they were taken to that page. Now they will be authenticated before they can see it.

**Comment by bunniseng** [comment]
@steverydz @pidpawel @chillkang 

by the way this is not fixed, it's actually worse, now when signing in I get a redirection loop with "OpenID transaction in progress" in the title with a blank screen.

**Comment by Lukewh** [comment]
@bunniseng is this still happening? Thanks

**Comment by Antvirf** [comment]
Still occurring
